/* TA-LIB Copyright (c) 1999-2008, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier (Replace when you are the original author)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  XXXXXX MF     Initial Version
 */

/**** START GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
/* All code within this section is automatically
 * generated by gen_code. Any modification will be lost
 * next time gen_code is run.
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */    #include "TA-Lib-Core.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode::InternalError)
/* Generated */    namespace TicTacTec { namespace TA { namespace Library {
/* Generated */ #elif defined( _JAVA )
/* Generated */    #include "ta_defs.h"
/* Generated */    #include "ta_java_defs.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode.InternalError)
/* Generated */ #else
/* Generated */    #include <string.h>
/* Generated */    #include <math.h>
/* Generated */    #include "ta_func.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_UTILITY_H
/* Generated */    #include "ta_utility.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_MEMORY_H
/* Generated */    #include "ta_memory.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #define TA_PREFIX(x) TA_##x
/* Generated */ #define INPUT_TYPE   double
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ int Core::RedkEverexLookback( int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                             MAType        optInMAType,/* Generated */                             int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                             MAType        optInRofMAType,/* Generated */                             double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                             int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                             MAType        optInSignalMAType,/* Generated */                             int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                             MAType        optInBiasMAType ) /* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public int redkEverexLookback( int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                              MAType        optInMAType,/* Generated */                              int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                              MAType        optInRofMAType,/* Generated */                              double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                              int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                              MAType        optInSignalMAType,/* Generated */                              int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                              MAType        optInBiasMAType ) /* Generated */ 
/* Generated */ #else
/* Generated */ TA_LIB_API int TA_REDK_EVEREX_Lookback( int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInMAType,/* Generated */                                                  int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInRofMAType,/* Generated */                                                  double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                                  int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInSignalMAType,/* Generated */                                                  int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInBiasMAType ) /* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */    /* min/max are checked for optInTimePeriod. */
/* Generated */    if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInTimePeriod = 30;
/* Generated */    else if( ((int)optInTimePeriod < 1) || ((int)optInTimePeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInMAType = (TA_MAType)0;
/* Generated */    else if( ((int)optInMAType < 0) || ((int)optInMAType > 9) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInRofPeriod. */
/* Generated */    if( (int)optInRofPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInRofPeriod = 10;
/* Generated */    else if( ((int)optInRofPeriod < 1) || ((int)optInRofPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInRofMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInRofMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInRofMAType < 0) || ((int)optInRofMAType > 9) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    if( optInRofSmooth == TA_REAL_DEFAULT )
/* Generated */       optInRofSmooth = 3.000000e+0;
/* Generated */    else if( (optInRofSmooth < 0.000000e+0) ||/* Generated */  (optInRofSmooth > 3.000000e+37) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInSignalPeriod. */
/* Generated */    if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInSignalPeriod = 5;
/* Generated */    else if( ((int)optInSignalPeriod < 1) || ((int)optInSignalPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInSignalMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInSignalMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInSignalMAType < 0) || ((int)optInSignalMAType > 9) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInBiasPeriod. */
/* Generated */    if( (int)optInBiasPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInBiasPeriod = 30;
/* Generated */    else if( ((int)optInBiasPeriod < 1) || ((int)optInBiasPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInBiasMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInBiasMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInBiasMAType < 0) || ((int)optInBiasMAType > 9) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/**** END GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/

   /* insert lookback code here. */

   return 0;
}

/**** START GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
/*
 * TA_REDK_EVEREX - RedK EVEREX - Effort Versus Results Explorer
 * 
 * Input  = Open, High, Low, Close, Volume
 * Output = double, double, double, double, double, double, double, double, double, double, double, int
 * 
 * Optional Parameters
 * -------------------
 * optInTimePeriod:(From 1 to 100000)
 *    Number of period
 * 
 * optInMAType:
 *    Type of Moving Average
 * 
 * optInRofPeriod:(From 1 to 100000)
 *    Rate of Flow Period
 * 
 * optInRofMAType:
 *    Type of ROF Moving Average
 * 
 * optInRofSmooth:(From 0 to TA_REAL_MAX)
 *    Rate of Flow Smooth
 * 
 * optInSignalPeriod:(From 1 to 100000)
 *    Signal Period
 * 
 * optInSignalMAType:
 *    Type of Signal Moving Average
 * 
 * optInBiasPeriod:(From 1 to 100000)
 *    Bias Period
 * 
 * optInBiasMAType:
 *    Type of Bias Moving Average
 * 
 * 
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::RedkEverex( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            SubArray<double>^ inOpen,
/* Generated */                                            SubArray<double>^ inHigh,
/* Generated */                                            SubArray<double>^ inLow,
/* Generated */                                            SubArray<double>^ inClose,
/* Generated */                                            SubArray<double>^ inVolume,
/* Generated */                                            int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInMAType,/* Generated */                                            int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInRofMAType,/* Generated */                                            double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                            int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSignalMAType,/* Generated */                                            int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInBiasMAType,/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            SubArray<double>^  outVolNorm,
/* Generated */                                            SubArray<double>^  outPriceNorm,
/* Generated */                                            SubArray<double>^  outFlow,
/* Generated */                                            SubArray<double>^  outBullAvg,
/* Generated */                                            SubArray<double>^  outBearAvg,
/* Generated */                                            SubArray<double>^  outRROF,
/* Generated */                                            SubArray<double>^  outRROFSmooth,
/* Generated */                                            SubArray<double>^  outSignal,
/* Generated */                                            SubArray<double>^  outBiasSentiment,
/* Generated */                                            SubArray<double>^  outBiasSentimentSmooth,
/* Generated */                                            SubArray<double>^  outEvRatio,
/* Generated */                                            SubArray<int>^  outFlowUp )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::RedkEverex( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            cli::array<double>^ inOpen,
/* Generated */                                            cli::array<double>^ inHigh,
/* Generated */                                            cli::array<double>^ inLow,
/* Generated */                                            cli::array<double>^ inClose,
/* Generated */                                            cli::array<double>^ inVolume,
/* Generated */                                            int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInMAType,/* Generated */                                            int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInRofMAType,/* Generated */                                            double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                            int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSignalMAType,/* Generated */                                            int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInBiasMAType,/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            cli::array<double>^  outVolNorm,
/* Generated */                                            cli::array<double>^  outPriceNorm,
/* Generated */                                            cli::array<double>^  outFlow,
/* Generated */                                            cli::array<double>^  outBullAvg,
/* Generated */                                            cli::array<double>^  outBearAvg,
/* Generated */                                            cli::array<double>^  outRROF,
/* Generated */                                            cli::array<double>^  outRROFSmooth,
/* Generated */                                            cli::array<double>^  outSignal,
/* Generated */                                            cli::array<double>^  outBiasSentiment,
/* Generated */                                            cli::array<double>^  outBiasSentimentSmooth,
/* Generated */                                            cli::array<double>^  outEvRatio,
/* Generated */                                            cli::array<int>^  outFlowUp )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverex( int    startIdx,
/* Generated */                            int    endIdx,
/* Generated */                            double       inOpen[],
/* Generated */                            double       inHigh[],
/* Generated */                            double       inLow[],
/* Generated */                            double       inClose[],
/* Generated */                            double       inVolume[],
/* Generated */                            int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInMAType,/* Generated */                            int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInRofMAType,/* Generated */                            double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                            int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInSignalMAType,/* Generated */                            int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInBiasMAType,/* Generated */                            MInteger     outBegIdx,
/* Generated */                            MInteger     outNBElement,
/* Generated */                            double        outVolNorm[],
/* Generated */                            double        outPriceNorm[],
/* Generated */                            double        outFlow[],
/* Generated */                            double        outBullAvg[],
/* Generated */                            double        outBearAvg[],
/* Generated */                            double        outRROF[],
/* Generated */                            double        outRROFSmooth[],
/* Generated */                            double        outSignal[],
/* Generated */                            double        outBiasSentiment[],
/* Generated */                            double        outBiasSentimentSmooth[],
/* Generated */                            double        outEvRatio[],
/* Generated */                            int           outFlowUp[] )
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_REDK_EVEREX( int    startIdx,
/* Generated */                                       int    endIdx,
/* Generated */                                                  const double inOpen[],
/* Generated */                                                  const double inHigh[],
/* Generated */                                                  const double inLow[],
/* Generated */                                                  const double inClose[],
/* Generated */                                                  const double inVolume[],
/* Generated */                                                  int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInMAType,/* Generated */                                                  int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInRofMAType,/* Generated */                                                  double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                                  int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInSignalMAType,/* Generated */                                                  int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                                  TA_MAType     optInBiasMAType,/* Generated */                                                  int          *outBegIdx,
/* Generated */                                                  int          *outNBElement,
/* Generated */                                                  double        outVolNorm[],
/* Generated */                                                  double        outPriceNorm[],
/* Generated */                                                  double        outFlow[],
/* Generated */                                                  double        outBullAvg[],
/* Generated */                                                  double        outBearAvg[],
/* Generated */                                                  double        outRROF[],
/* Generated */                                                  double        outRROFSmooth[],
/* Generated */                                                  double        outSignal[],
/* Generated */                                                  double        outBiasSentiment[],
/* Generated */                                                  double        outBiasSentimentSmooth[],
/* Generated */                                                  double        outEvRatio[],
/* Generated */                                                  int           outFlowUp[] )
/* Generated */ #endif
/**** END GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    /* Validate the requested output range. */
/* Generated */    if( startIdx < 0 )
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */    if( (endIdx < 0) || (endIdx < startIdx))
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */ 
/* Generated */    #if !defined(_JAVA)
/* Generated */    /* Verify required price component. */
/* Generated */    if(!inOpen||!inHigh||!inLow||!inClose||!inVolume)
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInTimePeriod. */
/* Generated */    if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInTimePeriod = 30;
/* Generated */    else if( ((int)optInTimePeriod < 1) || ((int)optInTimePeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInMAType = (TA_MAType)0;
/* Generated */    else if( ((int)optInMAType < 0) || ((int)optInMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInRofPeriod. */
/* Generated */    if( (int)optInRofPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInRofPeriod = 10;
/* Generated */    else if( ((int)optInRofPeriod < 1) || ((int)optInRofPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInRofMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInRofMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInRofMAType < 0) || ((int)optInRofMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    if( optInRofSmooth == TA_REAL_DEFAULT )
/* Generated */       optInRofSmooth = 3.000000e+0;
/* Generated */    else if( (optInRofSmooth < 0.000000e+0) ||/* Generated */  (optInRofSmooth > 3.000000e+37) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInSignalPeriod. */
/* Generated */    if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInSignalPeriod = 5;
/* Generated */    else if( ((int)optInSignalPeriod < 1) || ((int)optInSignalPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInSignalMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInSignalMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInSignalMAType < 0) || ((int)optInSignalMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInBiasPeriod. */
/* Generated */    if( (int)optInBiasPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInBiasPeriod = 30;
/* Generated */    else if( ((int)optInBiasPeriod < 1) || ((int)optInBiasPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInBiasMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInBiasMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInBiasMAType < 0) || ((int)optInBiasMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    #if !defined(_JAVA)
/* Generated */    if( !outVolNorm )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outPriceNorm )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outFlow )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBullAvg )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBearAvg )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outRROF )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outRROFSmooth )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outSignal )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBiasSentiment )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBiasSentimentSmooth )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outEvRatio )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outFlowUp )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA) */
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/

   /* Insert TA function code here. */

   /* Default return values */
   VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
   VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);

   return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
}

/**** START GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ Core::RetCode Core::RedkEverexStateInit( struct TA_RedkEverex_State** _state,
/* Generated */                                        int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                        MAType        optInMAType,/* Generated */                                        int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                        MAType        optInRofMAType,/* Generated */                                        double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                        int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                        MAType        optInSignalMAType,/* Generated */                                        int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                        MAType        optInBiasMAType ) /* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverexStateInit( struct TA_redkEverex_State** _state,
/* Generated */                                   int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                   MAType        optInMAType,/* Generated */                                   int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                   MAType        optInRofMAType,/* Generated */                                   double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                   int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                   MAType        optInSignalMAType,/* Generated */                                   int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                   MAType        optInBiasMAType ) /* Generated */ 
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_REDK_EVEREX_StateInit( struct TA_REDK_EVEREX_State** _state,
/* Generated */                                                          int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                                          TA_MAType     optInMAType,/* Generated */                                                          int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                                          TA_MAType     optInRofMAType,/* Generated */                                                          double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                                          int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                                          TA_MAType     optInSignalMAType,/* Generated */                                                          int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                                          TA_MAType     optInBiasMAType ) /* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 6 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    if (_state == NULL)
/* Generated */          return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    /* min/max are checked for optInTimePeriod. */
/* Generated */    if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInTimePeriod = 30;
/* Generated */    else if( ((int)optInTimePeriod < 1) || ((int)optInTimePeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInMAType = (TA_MAType)0;
/* Generated */    else if( ((int)optInMAType < 0) || ((int)optInMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInRofPeriod. */
/* Generated */    if( (int)optInRofPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInRofPeriod = 10;
/* Generated */    else if( ((int)optInRofPeriod < 1) || ((int)optInRofPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInRofMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInRofMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInRofMAType < 0) || ((int)optInRofMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    if( optInRofSmooth == TA_REAL_DEFAULT )
/* Generated */       optInRofSmooth = 3.000000e+0;
/* Generated */    else if( (optInRofSmooth < 0.000000e+0) ||/* Generated */  (optInRofSmooth > 3.000000e+37) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInSignalPeriod. */
/* Generated */    if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInSignalPeriod = 5;
/* Generated */    else if( ((int)optInSignalPeriod < 1) || ((int)optInSignalPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInSignalMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInSignalMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInSignalMAType < 0) || ((int)optInSignalMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInBiasPeriod. */
/* Generated */    if( (int)optInBiasPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInBiasPeriod = 30;
/* Generated */    else if( ((int)optInBiasPeriod < 1) || ((int)optInBiasPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInBiasMAType == TA_INTEGER_DEFAULT )
/* Generated */       optInBiasMAType = (TA_MAType)2;
/* Generated */    else if( ((int)optInBiasMAType < 0) || ((int)optInBiasMAType > 9) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    STATE = TA_Calloc(1, sizeof(struct TA_REDK_EVEREX_State));
/* Generated */    STATE_P.mem_index = 0;
/* Generated */    STATE_P.optInTimePeriod = optInTimePeriod;
/* Generated */    STATE_P.optInMAType = optInMAType;
/* Generated */    STATE_P.optInRofPeriod = optInRofPeriod;
/* Generated */    STATE_P.optInRofMAType = optInRofMAType;
/* Generated */    STATE_P.optInRofSmooth = optInRofSmooth;
/* Generated */    STATE_P.optInSignalPeriod = optInSignalPeriod;
/* Generated */    STATE_P.optInSignalMAType = optInSignalMAType;
/* Generated */    STATE_P.optInBiasPeriod = optInBiasPeriod;
/* Generated */    STATE_P.optInBiasMAType = optInBiasMAType;
/* Generated */    MEM_SIZE_P = TA_REDK_EVEREX_Lookback(optInTimePeriod, optInMAType, optInRofPeriod, optInRofMAType, optInRofSmooth, optInSignalPeriod, optInSignalMAType, optInBiasPeriod, optInBiasMAType );
/* Generated */    #ifndef TA_REDK_EVEREX_SUPPRESS_MEMORY_ALLOCATION
/* Generated */    if (MEM_SIZE_P > 0)
/* Generated */          MEM_P = TA_Calloc(MEM_SIZE_P, sizeof(struct TA_REDK_EVEREX_Data));
/* Generated */    else
/* Generated */    #endif
/* Generated */          MEM_P = NULL;/* Generated */ 
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 6 - DO NOT DELETE THIS LINE ****/

   /* insert state init code here. */

   _state = NULL;
   return 0;
}

/**** START GENCODE SECTION 7 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ Core::RetCode Core::RedkEverexState( struct TA_RedkEverex_State* _state,
/* Generated */                                    cli::array<double>^ inOpen,
/* Generated */                                    cli::array<double>^ inHigh,
/* Generated */                                    cli::array<double>^ inLow,
/* Generated */                                    cli::array<double>^ inClose,
/* Generated */                                    cli::array<double>^ inVolume,
/* Generated */                                    cli::array<double>^  *outVolNorm,
/* Generated */                                    cli::array<double>^  *outPriceNorm,
/* Generated */                                    cli::array<double>^  *outFlow,
/* Generated */                                    cli::array<double>^  *outBullAvg,
/* Generated */                                    cli::array<double>^  *outBearAvg,
/* Generated */                                    cli::array<double>^  *outRROF,
/* Generated */                                    cli::array<double>^  *outRROFSmooth,
/* Generated */                                    cli::array<double>^  *outSignal,
/* Generated */                                    cli::array<double>^  *outBiasSentiment,
/* Generated */                                    cli::array<double>^  *outBiasSentimentSmooth,
/* Generated */                                    cli::array<double>^  *outEvRatio,
/* Generated */                                    cli::array<int>^  *outFlowUp )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverexState( struct TA_redkEverex_State* _state,
/* Generated */                               double       inOpen,
/* Generated */                               double       inHigh,
/* Generated */                               double       inLow,
/* Generated */                               double       inClose,
/* Generated */                               double       inVolume,
/* Generated */                               double        *outVolNorm,
/* Generated */                               double        *outPriceNorm,
/* Generated */                               double        *outFlow,
/* Generated */                               double        *outBullAvg,
/* Generated */                               double        *outBearAvg,
/* Generated */                               double        *outRROF,
/* Generated */                               double        *outRROFSmooth,
/* Generated */                               double        *outSignal,
/* Generated */                               double        *outBiasSentiment,
/* Generated */                               double        *outBiasSentimentSmooth,
/* Generated */                               double        *outEvRatio,
/* Generated */                               int           *outFlowUp )
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_REDK_EVEREX_State( struct TA_REDK_EVEREX_State* _state,
/* Generated */                                                      const double inOpen,
/* Generated */                                                      const double inHigh,
/* Generated */                                                      const double inLow,
/* Generated */                                                      const double inClose,
/* Generated */                                                      const double inVolume,
/* Generated */                                                      double        *outVolNorm,
/* Generated */                                                      double        *outPriceNorm,
/* Generated */                                                      double        *outFlow,
/* Generated */                                                      double        *outBullAvg,
/* Generated */                                                      double        *outBearAvg,
/* Generated */                                                      double        *outRROF,
/* Generated */                                                      double        *outRROFSmooth,
/* Generated */                                                      double        *outSignal,
/* Generated */                                                      double        *outBiasSentiment,
/* Generated */                                                      double        *outBiasSentimentSmooth,
/* Generated */                                                      double        *outEvRatio,
/* Generated */                                                      int           *outFlowUp )
/* Generated */ #endif
/**** END GENCODE SECTION 7 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 8 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    if (_state == NULL)
/* Generated */          return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    #if !defined(_JAVA)
/* Generated */    #endif /* !defined(_JAVA)*/
/* Generated */    size_t _cur_idx = STATE.mem_index++;
/* Generated */    if (MEM_SIZE > 0) _cur_idx %= MEM_SIZE;
/* Generated */    UNUSED_VARIABLE(_cur_idx); // in case PUSH\POP methods won't be used
/* Generated */    #ifndef TA_REDK_EVEREX_SUPPRESS_EXIT_ON_NOT_ENOUGH_DATA
/* Generated */    if (NEED_MORE_DATA) {
/* Generated */          PUSH_TO_MEM(inOpen,inOpen);
/* Generated */          PUSH_TO_MEM(inHigh,inHigh);
/* Generated */          PUSH_TO_MEM(inLow,inLow);
/* Generated */          PUSH_TO_MEM(inClose,inClose);
/* Generated */          PUSH_TO_MEM(inVolume,inVolume);
/* Generated */    return ENUM_VALUE(RetCode,TA_NEED_MORE_DATA,NeedMoreData); }
/* Generated */    #endif
/* Generated */    #if !defined(_JAVA)
/* Generated */    if( !outVolNorm )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outPriceNorm )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outFlow )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBullAvg )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBearAvg )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outRROF )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outRROFSmooth )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outSignal )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBiasSentiment )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBiasSentimentSmooth )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outEvRatio )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outFlowUp )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA) */
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 8 - DO NOT DELETE THIS LINE ****/

   /* insert state based TA func code here. */

   return 0;
}

/**** START GENCODE SECTION 9 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ Core::RetCode Core::RedkEverexBatchState( struct TA_RedkEverex_State* _state,
/* Generated */                                         int startIdx,
/* Generated */                                         int endIdx,
/* Generated */                                         cli::array<double>^ inOpen,
/* Generated */                                         cli::array<double>^ inHigh,
/* Generated */                                         cli::array<double>^ inLow,
/* Generated */                                         cli::array<double>^ inClose,
/* Generated */                                         cli::array<double>^ inVolume,
/* Generated */                                         [Out]int%    outBegIdx,
/* Generated */                                         [Out]int%    outNBElement,
/* Generated */                                         cli::array<double>^  outVolNorm,
/* Generated */                                         cli::array<double>^  outPriceNorm,
/* Generated */                                         cli::array<double>^  outFlow,
/* Generated */                                         cli::array<double>^  outBullAvg,
/* Generated */                                         cli::array<double>^  outBearAvg,
/* Generated */                                         cli::array<double>^  outRROF,
/* Generated */                                         cli::array<double>^  outRROFSmooth,
/* Generated */                                         cli::array<double>^  outSignal,
/* Generated */                                         cli::array<double>^  outBiasSentiment,
/* Generated */                                         cli::array<double>^  outBiasSentimentSmooth,
/* Generated */                                         cli::array<double>^  outEvRatio,
/* Generated */                                         cli::array<int>^  outFlowUp )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverexBatchState( struct TA_redkEverex_State* _state,
/* Generated */                                    int startIdx,
/* Generated */                                    int endIdx,
/* Generated */                                    double       inOpen[],
/* Generated */                                    double       inHigh[],
/* Generated */                                    double       inLow[],
/* Generated */                                    double       inClose[],
/* Generated */                                    double       inVolume[],
/* Generated */                                    MInteger     outBegIdx,
/* Generated */                                    MInteger     outNBElement,
/* Generated */                                    double        outVolNorm[],
/* Generated */                                    double        outPriceNorm[],
/* Generated */                                    double        outFlow[],
/* Generated */                                    double        outBullAvg[],
/* Generated */                                    double        outBearAvg[],
/* Generated */                                    double        outRROF[],
/* Generated */                                    double        outRROFSmooth[],
/* Generated */                                    double        outSignal[],
/* Generated */                                    double        outBiasSentiment[],
/* Generated */                                    double        outBiasSentimentSmooth[],
/* Generated */                                    double        outEvRatio[],
/* Generated */                                    int           outFlowUp[] )
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_REDK_EVEREX_BatchState( struct TA_REDK_EVEREX_State* _state,
/* Generated */                                                           int startIdx,
/* Generated */                                                           int endIdx,
/* Generated */                                                           const double inOpen[],
/* Generated */                                                           const double inHigh[],
/* Generated */                                                           const double inLow[],
/* Generated */                                                           const double inClose[],
/* Generated */                                                           const double inVolume[],
/* Generated */                                                           int          *outBegIdx,
/* Generated */                                                           int          *outNBElement,
/* Generated */                                                           double        outVolNorm[],
/* Generated */                                                           double        outPriceNorm[],
/* Generated */                                                           double        outFlow[],
/* Generated */                                                           double        outBullAvg[],
/* Generated */                                                           double        outBearAvg[],
/* Generated */                                                           double        outRROF[],
/* Generated */                                                           double        outRROFSmooth[],
/* Generated */                                                           double        outSignal[],
/* Generated */                                                           double        outBiasSentiment[],
/* Generated */                                                           double        outBiasSentimentSmooth[],
/* Generated */                                                           double        outEvRatio[],
/* Generated */                                                           int           outFlowUp[] )
/* Generated */ #endif
/**** END GENCODE SECTION 9 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 10 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_OVERWRITE_BATCH_STATE_CODE
/* Generated */ 
/* Generated */    if (_state == NULL)
/* Generated */          return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    #if !defined(_JAVA)
/* Generated */    /* Verify required price component. */
/* Generated */    if(!inOpen||!inHigh||!inLow||!inClose||!inVolume)
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA)*/
/* Generated */    #if !defined(_JAVA)
/* Generated */    if( !outVolNorm )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outPriceNorm )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outFlow )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBullAvg )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBearAvg )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outRROF )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outRROFSmooth )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outSignal )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBiasSentiment )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outBiasSentimentSmooth )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outEvRatio )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outFlowUp )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA) */
/* Generated */    /* Make sure there is still something to evaluate. */
/* Generated */    if( startIdx > endIdx )
/* Generated */    {
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */       return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */    }
/* Generated */    
/* Generated */    
/* Generated */    double outVolNormVal;
/* Generated */    double outPriceNormVal;
/* Generated */    double outFlowVal;
/* Generated */    double outBullAvgVal;
/* Generated */    double outBearAvgVal;
/* Generated */    double outRROFVal;
/* Generated */    double outRROFSmoothVal;
/* Generated */    double outSignalVal;
/* Generated */    double outBiasSentimentVal;
/* Generated */    double outBiasSentimentSmoothVal;
/* Generated */    double outEvRatioVal;
/* Generated */    int outFlowUpVal;
/* Generated */    int retValue;
/* Generated */    
/* Generated */    int outIdx = 0;
/* Generated */    VALUE_HANDLE_DEREF(outBegIdx)  = startIdx;
/* Generated */    
/* Generated */    for (int i = startIdx; i <= endIdx; ++i, outIdx++) {
/* Generated */       retValue = TA_REDK_EVEREX_State( _state, inOpen[i], inHigh[i], inLow[i], inClose[i], inVolume[i], &outVolNormVal, &outPriceNormVal, &outFlowVal, &outBullAvgVal, &outBearAvgVal, &outRROFVal, &outRROFSmoothVal, &outSignalVal, &outBiasSentimentVal, &outBiasSentimentSmoothVal, &outEvRatioVal, &outFlowUpVal );
/* Generated */       if ( retValue == ENUM_VALUE(RetCode,TA_SUCCESS,Success) ) {
/* Generated */          outVolNorm[outIdx] = outVolNormVal;
/* Generated */          outPriceNorm[outIdx] = outPriceNormVal;
/* Generated */          outFlow[outIdx] = outFlowVal;
/* Generated */          outBullAvg[outIdx] = outBullAvgVal;
/* Generated */          outBearAvg[outIdx] = outBearAvgVal;
/* Generated */          outRROF[outIdx] = outRROFVal;
/* Generated */          outRROFSmooth[outIdx] = outRROFSmoothVal;
/* Generated */          outSignal[outIdx] = outSignalVal;
/* Generated */          outBiasSentiment[outIdx] = outBiasSentimentVal;
/* Generated */          outBiasSentimentSmooth[outIdx] = outBiasSentimentSmoothVal;
/* Generated */          outEvRatio[outIdx] = outEvRatioVal;
/* Generated */          outFlowUp[outIdx] = outFlowUpVal;
/* Generated */       } else if ( retValue == ENUM_VALUE(RetCode,TA_NEED_MORE_DATA,NeedMoreData) ) {
/* Generated */          outVolNorm[outIdx] = NAN;
/* Generated */          outPriceNorm[outIdx] = NAN;
/* Generated */          outFlow[outIdx] = NAN;
/* Generated */          outBullAvg[outIdx] = NAN;
/* Generated */          outBearAvg[outIdx] = NAN;
/* Generated */          outRROF[outIdx] = NAN;
/* Generated */          outRROFSmooth[outIdx] = NAN;
/* Generated */          outSignal[outIdx] = NAN;
/* Generated */          outBiasSentiment[outIdx] = NAN;
/* Generated */          outBiasSentimentSmooth[outIdx] = NAN;
/* Generated */          outEvRatio[outIdx] = NAN;
/* Generated */          outFlowUp[outIdx] = INT_MAX;
/* Generated */       } else {
/* Generated */          break;
/* Generated */        }
/* Generated */    }
/* Generated */    
/* Generated */    VALUE_HANDLE_DEREF(outNBElement) = outIdx;
/* Generated */ #endif /* TA_OVERWRITE_BATCH_STATE_CODE */
/* Generated */ 
/**** END GENCODE SECTION 10 - DO NOT DELETE THIS LINE ****/

   /* insert batch state code here. */
   return retValue;
}

/**** START GENCODE SECTION 11 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ Core::RetCode Core::RedkEverexStateFree( struct TA_RedkEverex_State** _state )
/* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverexStateFree( struct TA_redkEverex_State** _state )
/* Generated */ 
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_REDK_EVEREX_StateFree( struct TA_REDK_EVEREX_State** _state )
/* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 11 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 12 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    if (_state == NULL)
/* Generated */          return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    if (STATE != NULL) {
/* Generated */          if (MEM_P != NULL) TA_Free(MEM_P);
/* Generated */          TA_Free(STATE); STATE = NULL;}
/* Generated */ 
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 12 - DO NOT DELETE THIS LINE ****/

   /* insert state free code here. */   
   return 0;
}

/**** START GENCODE SECTION 13 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ Core::RetCode Core::RedkEverexStateSave( struct TA_RedkEverex_State* _state,
/* Generated */                                        FILE* _file )
/* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverexStateSave( struct TA_redkEverex_State* _state,
/* Generated */                                   FILE* _file )
/* Generated */ 
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_REDK_EVEREX_StateSave( struct TA_REDK_EVEREX_State* _state,
/* Generated */                                                          FILE* _file )
/* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 13 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 14 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */     int io_res; int state_is_null; state_is_null = (_state == NULL);
/* Generated */    io_res = fwrite(&state_is_null,sizeof(state_is_null),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    if (state_is_null) return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */    io_res = fwrite(&STATE.mem_index,sizeof(STATE.mem_index),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.mem_size,sizeof(STATE.mem_size),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    int memory_allocated;
/* Generated */    memory_allocated = STATE.memory != NULL;
/* Generated */    io_res = fwrite(&memory_allocated,sizeof(memory_allocated),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    if (memory_allocated && STATE.mem_size > 0) { io_res = fwrite(STATE.memory,sizeof(struct TA_REDK_EVEREX_Data),STATE.mem_size,_file);
/* Generated */    if (io_res < (int) STATE.mem_size) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed); }
/* Generated */    io_res = fwrite(&STATE.optInTimePeriod,sizeof(STATE.optInTimePeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInMAType,sizeof(STATE.optInMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInRofPeriod,sizeof(STATE.optInRofPeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInRofMAType,sizeof(STATE.optInRofMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInRofSmooth,sizeof(STATE.optInRofSmooth),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInSignalPeriod,sizeof(STATE.optInSignalPeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInSignalMAType,sizeof(STATE.optInSignalMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInBiasPeriod,sizeof(STATE.optInBiasPeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fwrite(&STATE.optInBiasMAType,sizeof(STATE.optInBiasMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    // Warning: STATE.StateVolMA must be saved manually!
/* Generated */    // Warning: STATE.StateBarSpreadMA must be saved manually!
/* Generated */    // Warning: STATE.StateSrcShiftMA must be saved manually!
/* Generated */    // Warning: STATE.StateBullMA must be saved manually!
/* Generated */    // Warning: STATE.StateBearMA must be saved manually!
/* Generated */    // Warning: STATE.StateRrofMA must be saved manually!
/* Generated */    // Warning: STATE.StateRrofSmootMA must be saved manually!
/* Generated */    // Warning: STATE.StateSignalMA must be saved manually!
/* Generated */    // Warning: STATE.StateBiasBullMA must be saved manually!
/* Generated */    // Warning: STATE.StateBiasBearMA must be saved manually!
/* Generated */    // Warning: STATE.StateBiasSmoothMA must be saved manually!
/* Generated */    // Warning: STATE.StateBullSmoothWMA must be saved manually!
/* Generated */    // Warning: STATE.StateBearSmoothWMA must be saved manually!
/* Generated */    // Warning: STATE.StateBullMax must be saved manually!
/* Generated */    // Warning: STATE.StateBearMin must be saved manually!
/* Generated */    // Warning: STATE.StateMinPriceN must be saved manually!
/* Generated */    // Warning: STATE.StateMaxNPrice must be saved manually!
/* Generated */    // Warning: STATE.StateMinVolN must be saved manually!
/* Generated */    // Warning: STATE.StateMaxNVol must be saved manually!
/* Generated */ 
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 14 - DO NOT DELETE THIS LINE ****/

   /* insert state save code here. */   
   return 0;
}

/**** START GENCODE SECTION 15 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ Core::RetCode Core::RedkEverexStateLoad( struct TA_RedkEverex_State** _state,
/* Generated */                                        FILE* _file )
/* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverexStateLoad( struct TA_redkEverex_State** _state,
/* Generated */                                   FILE* _file )
/* Generated */ 
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_REDK_EVEREX_StateLoad( struct TA_REDK_EVEREX_State** _state,
/* Generated */                                                          FILE* _file )
/* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 15 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 16 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    int io_res; int state_is_null;
/* Generated */    io_res = fread(&state_is_null,sizeof(state_is_null),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    if (state_is_null) return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */    if (STATE != NULL) return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    STATE = TA_Calloc(1, sizeof(struct TA_REDK_EVEREX_State));
/* Generated */    io_res = fread(&STATE_P.mem_index,sizeof(STATE_P.mem_index),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.mem_size,sizeof(STATE_P.mem_size),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    int memory_allocated;
/* Generated */    io_res = fread(&memory_allocated,sizeof(memory_allocated),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    if (STATE_P.mem_size > 0 && memory_allocated) { STATE_P.memory = TA_Calloc(STATE_P.mem_size, sizeof(struct TA_REDK_EVEREX_Data));
/* Generated */    io_res = fread(STATE_P.memory,sizeof(struct TA_REDK_EVEREX_Data),STATE_P.mem_size,_file);
/* Generated */    if (io_res < (int) STATE_P.mem_size) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed); } 
/* Generated */    io_res = fread(&STATE_P.optInTimePeriod,sizeof(STATE_P.optInTimePeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInMAType,sizeof(STATE_P.optInMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInRofPeriod,sizeof(STATE_P.optInRofPeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInRofMAType,sizeof(STATE_P.optInRofMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInRofSmooth,sizeof(STATE_P.optInRofSmooth),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInSignalPeriod,sizeof(STATE_P.optInSignalPeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInSignalMAType,sizeof(STATE_P.optInSignalMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInBiasPeriod,sizeof(STATE_P.optInBiasPeriod),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    io_res = fread(&STATE_P.optInBiasMAType,sizeof(STATE_P.optInBiasMAType),1,_file);
/* Generated */    if (io_res < 1) return ENUM_VALUE(RetCode,TA_IO_FAILED,IOFailed);
/* Generated */    // Warning: STATE_P.StateVolMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBarSpreadMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateSrcShiftMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBullMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBearMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateRrofMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateRrofSmootMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateSignalMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBiasBullMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBiasBearMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBiasSmoothMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBullSmoothWMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBearSmoothWMA must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBullMax must be loaded manually!
/* Generated */    // Warning: STATE_P.StateBearMin must be loaded manually!
/* Generated */    // Warning: STATE_P.StateMinPriceN must be loaded manually!
/* Generated */    // Warning: STATE_P.StateMaxNPrice must be loaded manually!
/* Generated */    // Warning: STATE_P.StateMinVolN must be loaded manually!
/* Generated */    // Warning: STATE_P.StateMaxNVol must be loaded manually!
/* Generated */ 
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 16 - DO NOT DELETE THIS LINE ****/

   /* insert state load code here. */   
   return 0;
}

/**** START GENCODE SECTION 17 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #define  USE_SINGLE_PRECISION_INPUT
/* Generated */ #undef  TA_LIB_PRO
/* Generated */ #if !defined( _MANAGED ) && !defined( _JAVA )
/* Generated */    #undef   TA_PREFIX
/* Generated */    #define  TA_PREFIX(x) TA_S_##x
/* Generated */ #endif
/* Generated */ #undef   INPUT_TYPE
/* Generated */ #define  INPUT_TYPE float
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::RedkEverex( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            SubArray<float>^ inOpen,
/* Generated */                                            SubArray<float>^ inHigh,
/* Generated */                                            SubArray<float>^ inLow,
/* Generated */                                            SubArray<float>^ inClose,
/* Generated */                                            SubArray<float>^ inVolume,
/* Generated */                                            int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInMAType,/* Generated */                                            int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInRofMAType,/* Generated */                                            double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                            int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSignalMAType,/* Generated */                                            int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInBiasMAType,/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            SubArray<double>^  outVolNorm,
/* Generated */                                            SubArray<double>^  outPriceNorm,
/* Generated */                                            SubArray<double>^  outFlow,
/* Generated */                                            SubArray<double>^  outBullAvg,
/* Generated */                                            SubArray<double>^  outBearAvg,
/* Generated */                                            SubArray<double>^  outRROF,
/* Generated */                                            SubArray<double>^  outRROFSmooth,
/* Generated */                                            SubArray<double>^  outSignal,
/* Generated */                                            SubArray<double>^  outBiasSentiment,
/* Generated */                                            SubArray<double>^  outBiasSentimentSmooth,
/* Generated */                                            SubArray<double>^  outEvRatio,
/* Generated */                                            SubArray<int>^  outFlowUp )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::RedkEverex( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            cli::array<float>^ inOpen,
/* Generated */                                            cli::array<float>^ inHigh,
/* Generated */                                            cli::array<float>^ inLow,
/* Generated */                                            cli::array<float>^ inClose,
/* Generated */                                            cli::array<float>^ inVolume,
/* Generated */                                            int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInMAType,/* Generated */                                            int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInRofMAType,/* Generated */                                            double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                                            int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSignalMAType,/* Generated */                                            int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                                            MAType        optInBiasMAType,/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            cli::array<double>^  outVolNorm,
/* Generated */                                            cli::array<double>^  outPriceNorm,
/* Generated */                                            cli::array<double>^  outFlow,
/* Generated */                                            cli::array<double>^  outBullAvg,
/* Generated */                                            cli::array<double>^  outBearAvg,
/* Generated */                                            cli::array<double>^  outRROF,
/* Generated */                                            cli::array<double>^  outRROFSmooth,
/* Generated */                                            cli::array<double>^  outSignal,
/* Generated */                                            cli::array<double>^  outBiasSentiment,
/* Generated */                                            cli::array<double>^  outBiasSentimentSmooth,
/* Generated */                                            cli::array<double>^  outEvRatio,
/* Generated */                                            cli::array<int>^  outFlowUp )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode redkEverex( int    startIdx,
/* Generated */                            int    endIdx,
/* Generated */                            float        inOpen[],
/* Generated */                            float        inHigh[],
/* Generated */                            float        inLow[],
/* Generated */                            float        inClose[],
/* Generated */                            float        inVolume[],
/* Generated */                            int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInMAType,/* Generated */                            int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInRofMAType,/* Generated */                            double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                            int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInSignalMAType,/* Generated */                            int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                            MAType        optInBiasMAType,/* Generated */                            MInteger     outBegIdx,
/* Generated */                            MInteger     outNBElement,
/* Generated */                            double        outVolNorm[],
/* Generated */                            double        outPriceNorm[],
/* Generated */                            double        outFlow[],
/* Generated */                            double        outBullAvg[],
/* Generated */                            double        outBearAvg[],
/* Generated */                            double        outRROF[],
/* Generated */                            double        outRROFSmooth[],
/* Generated */                            double        outSignal[],
/* Generated */                            double        outBiasSentiment[],
/* Generated */                            double        outBiasSentimentSmooth[],
/* Generated */                            double        outEvRatio[],
/* Generated */                            int           outFlowUp[] )
/* Generated */ #else
/* Generated */ TA_RetCode TA_S_REDK_EVEREX( int    startIdx,
/* Generated */                              int    endIdx,
/* Generated */                              const float  inOpen[],
/* Generated */                              const float  inHigh[],
/* Generated */                              const float  inLow[],
/* Generated */                              const float  inClose[],
/* Generated */                              const float  inVolume[],
/* Generated */                              int           optInTimePeriod, /* From 1 to 100000 */
/* Generated */                              TA_MAType     optInMAType,/* Generated */                              int           optInRofPeriod, /* From 1 to 100000 */
/* Generated */                              TA_MAType     optInRofMAType,/* Generated */                              double        optInRofSmooth, /* From 0 to TA_REAL_MAX */
/* Generated */                              int           optInSignalPeriod, /* From 1 to 100000 */
/* Generated */                              TA_MAType     optInSignalMAType,/* Generated */                              int           optInBiasPeriod, /* From 1 to 100000 */
/* Generated */                              TA_MAType     optInBiasMAType,/* Generated */                              int          *outBegIdx,
/* Generated */                              int          *outNBElement,
/* Generated */                              double        outVolNorm[],
/* Generated */                              double        outPriceNorm[],
/* Generated */                              double        outFlow[],
/* Generated */                              double        outBullAvg[],
/* Generated */                              double        outBearAvg[],
/* Generated */                              double        outRROF[],
/* Generated */                              double        outRROFSmooth[],
/* Generated */                              double        outSignal[],
/* Generated */                              double        outBiasSentiment[],
/* Generated */                              double        outBiasSentimentSmooth[],
/* Generated */                              double        outEvRatio[],
/* Generated */                              int           outFlowUp[] )
/* Generated */ #endif
/* Generated */ {
/* Generated */  #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */     if( startIdx < 0 )
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */     if( (endIdx < 0) || (endIdx < startIdx))
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */     #if !defined(_JAVA)
/* Generated */     if(!inOpen||!inHigh||!inLow||!inClose||!inVolume)
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */     if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInTimePeriod = 30;
/* Generated */     else if( ((int)optInTimePeriod < 1) || ((int)optInTimePeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */     if( (int)optInMAType == TA_INTEGER_DEFAULT )
/* Generated */        optInMAType = (TA_MAType)0;
/* Generated */     else if( ((int)optInMAType < 0) || ((int)optInMAType > 9) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */     if( (int)optInRofPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInRofPeriod = 10;
/* Generated */     else if( ((int)optInRofPeriod < 1) || ((int)optInRofPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */     if( (int)optInRofMAType == TA_INTEGER_DEFAULT )
/* Generated */        optInRofMAType = (TA_MAType)2;
/* Generated */     else if( ((int)optInRofMAType < 0) || ((int)optInRofMAType > 9) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */     if( optInRofSmooth == TA_REAL_DEFAULT )
/* Generated */        optInRofSmooth = 3.000000e+0;
/* Generated */     else if( (optInRofSmooth < 0.000000e+0) ||  (optInRofSmooth > 3.000000e+37) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInSignalPeriod = 5;
/* Generated */     else if( ((int)optInSignalPeriod < 1) || ((int)optInSignalPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */     if( (int)optInSignalMAType == TA_INTEGER_DEFAULT )
/* Generated */        optInSignalMAType = (TA_MAType)2;
/* Generated */     else if( ((int)optInSignalMAType < 0) || ((int)optInSignalMAType > 9) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */     if( (int)optInBiasPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInBiasPeriod = 30;
/* Generated */     else if( ((int)optInBiasPeriod < 1) || ((int)optInBiasPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */     if( (int)optInBiasMAType == TA_INTEGER_DEFAULT )
/* Generated */        optInBiasMAType = (TA_MAType)2;
/* Generated */     else if( ((int)optInBiasMAType < 0) || ((int)optInBiasMAType > 9) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */     #if !defined(_JAVA)
/* Generated */     if( !outVolNorm )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outPriceNorm )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outFlow )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outBullAvg )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outBearAvg )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outRROF )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outRROFSmooth )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outSignal )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outBiasSentiment )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outBiasSentimentSmooth )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outEvRatio )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outFlowUp )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */  #endif 
/* Generated */    VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */    VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */    return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */ }
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ }}} // Close namespace TicTacTec.TA.Lib
/* Generated */ #endif
/**** END GENCODE SECTION 17 - DO NOT DELETE THIS LINE ****/

